import os
import glob
from snakemake.utils import min_version

min_version('7.16.0')

configfile: '../config/hpcnode.yaml'

# Haplotype names. Used for finding haplotype fasta
HAPS = ['occ1', 'occ2', 'pall1', 'pall2']

# Input files
HAPLOTYPE_FASTA_DIR = config['haplotype_fastas']
HCN_LOCI_FASTA = config['hcn_loci_fasta']

# Paths for output files
LOG_DIR = config['log_prefix']
REF_DIR = f"{config['results_prefix']}/ref"
HCN_LOCI_DIR = f"{config['results_prefix']}/hcn_loci"
SYNTENY_DIR = f"{config['results_prefix']}/synteny"

include: 'rules/common.smk'

rule all:
    input:
        f'{REF_DIR}/ref.done',
        f'{HCN_LOCI_DIR}/hcn_loci.done',
        f'{SYNTENY_DIR}/synteny.done',


include: 'rules/ref.smk'
include: 'rules/hcn_loci.smk'
include: 'rules/synteny.smk'

