# Input files
resources: ../resources
TrR_five_fasta: /research/references/trifolium/repens/GCA_005869975.1_AgR_To_v5/GCA_005869975.1_AgR_To_v5_genomic.fna
genemark: /home/santang3/downloads/gmes_linux_64_4
prothint: /home/santang3/downloads/gmes_linux_64_4/ProtHint/bin

# Output
results_prefix: /research/projects/trifolium/dovetail/dcg/results
log_prefix: /research/projects/trifolium/dovetail/dcg/logs
