# Input files
haplotype_fastas: ../resources/haplotype_fastas/dovetail_v2
hcn_loci_fasta: ../resources/hcn_loci/T-repens_HCN_genes.fasta
repbase: ../resources/RepBaseRepeatMaskerEdition-20181026.tar.gz
genmap_files: /scratch/projects/trifolium/gwsd/toronto_gwsd/resources/genMap
rnaseq_accessions: ../resources/Trepens_rnaseq_accessions.txt

# Output
results_prefix: /scratch/projects/trifolium/dovetail/results
log_prefix: /scratch/projects/trifolium/dovetail/logs
