# Input files
haplotype_fastas: ../resources/haplotype_fastas
hcn_loci_fasta: ../resources/hcn_loci/T-repens_HCN_genes.fastai
genmap_files: /scratch/projects/trifolium/gwsd/toronto_gwsd/resources/genMap

# Output
results_prefix: /scratch/projects/trifolium/dovetail/results
log_prefix: /scratch/projects/trifolium/dovetail/logs
